package com.nxdcms.entity;
// Generated 2016-10-14 10:20:41 by Hibernate Tools 3.2.2.GA

/**
 * Administrator generated by hbm2java
 */
public class Administrator implements java.io.Serializable {

	private String administratorId;
	private String administratorPassword;
	private String administratorName;
	private String administratorCollege;
	private String administratorEmail;
	private String administratorPhnoe;

	public Administrator() {
	}

	public Administrator(String administratorId, String administratorPassword, String administratorName,
			String administratorCollege, String administratorEmail) {
		this.administratorId = administratorId;
		this.administratorPassword = administratorPassword;
		this.administratorName = administratorName;
		this.administratorCollege = administratorCollege;
		this.administratorEmail = administratorEmail;
	}

	public Administrator(String administratorId, String administratorPassword, String administratorName,
			String administratorCollege, String administratorEmail, String administratorPhnoe) {
		this.administratorId = administratorId;
		this.administratorPassword = administratorPassword;
		this.administratorName = administratorName;
		this.administratorCollege = administratorCollege;
		this.administratorEmail = administratorEmail;
		this.administratorPhnoe = administratorPhnoe;
	}

	public String getAdministratorId() {
		return this.administratorId;
	}

	public void setAdministratorId(String administratorId) {
		this.administratorId = administratorId;
	}

	public String getAdministratorPassword() {
		return this.administratorPassword;
	}

	public void setAdministratorPassword(String administratorPassword) {
		this.administratorPassword = administratorPassword;
	}

	public String getAdministratorName() {
		return this.administratorName;
	}

	public void setAdministratorName(String administratorName) {
		this.administratorName = administratorName;
	}

	public String getAdministratorCollege() {
		return this.administratorCollege;
	}

	public void setAdministratorCollege(String administratorCollege) {
		this.administratorCollege = administratorCollege;
	}

	public String getAdministratorEmail() {
		return this.administratorEmail;
	}

	public void setAdministratorEmail(String administratorEmail) {
		this.administratorEmail = administratorEmail;
	}

	public String getAdministratorPhnoe() {
		return this.administratorPhnoe;
	}

	public void setAdministratorPhnoe(String administratorPhnoe) {
		this.administratorPhnoe = administratorPhnoe;
	}

}
