package com.nxdcms.entity;
// Generated 2016-8-29 17:16:52 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.Set;

/**
 * Competition generated by hbm2java
 */
public class Competition implements java.io.Serializable {

	private Integer comId;
	private String comName;
	private String scale;
	private int type;
	private String holdingUnit;
	private Date enterStart;
	private Date publishTime;
	private Date enterStop;
	private String comContent;
	private String comLink;
	private String comLinkPath;
	private String issuer;
	private int flag;
	private Set<Subcompetition> subcompetitions ;
	public Integer getComId() {
		return comId;
	}
	public void setComId(Integer comId) {
		this.comId = comId;
	}
	public String getComName() {
		return comName;
	}
	public void setComName(String comName) {
		this.comName = comName;
	}
	public String getScale() {
		return scale;
	}
	public void setScale(String scale) {
		this.scale = scale;
	}
	public int getType() {
		return type;
	}
	public void setType(int type) {
		this.type = type;
	}
	public String getHoldingUnit() {
		return holdingUnit;
	}
	public void setHoldingUnit(String holdingUnit) {
		this.holdingUnit = holdingUnit;
	}
	public Date getEnterStart() {
		return enterStart;
	}
	public void setEnterStart(Date enterStart) {
		this.enterStart = enterStart;
	}
	public Date getPublishTime() {
		return publishTime;
	}
	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}
	public Date getEnterStop() {
		return enterStop;
	}
	public void setEnterStop(Date enterStop) {
		this.enterStop = enterStop;
	}
	public String getComContent() {
		return comContent;
	}
	public void setComContent(String comContent) {
		this.comContent = comContent;
	}
	public String getComLink() {
		return comLink;
	}
	public void setComLink(String comLink) {
		this.comLink = comLink;
	}
	public String getComLinkPath() {
		return comLinkPath;
	}
	public void setComLinkPath(String comLinkPath) {
		this.comLinkPath = comLinkPath;
	}
	public String getIssuer() {
		return issuer;
	}
	public void setIssuer(String issuer) {
		this.issuer = issuer;
	}

	public int getFlag() {
		return flag;
	}
	public void setFlag(int flag) {
		this.flag = flag;
	}
	public Set<Subcompetition> getSubcompetitions() {
		return subcompetitions;
	}
	public void setSubcompetitions(Set<Subcompetition> subcompetitions) {
		this.subcompetitions = subcompetitions;
	}
	@Override
	public String toString() {
		return "Competition [comId=" + comId + ", comName=" + comName + "]";
	}
	
	
	
}
