package com.nxdcms.entity;
// Generated 2016-7-25 10:50:34 by Hibernate Tools 3.2.2.GA

import java.util.Arrays;

/**
 * News generated by hbm2java
 */
public class News implements java.io.Serializable {

	private String newsTitle;
	private String newsContent;
	private String newsIssuedate;
	private String newsIssuer;
	private String newsPhotoName;
	private String newsPhotoPath;
	
	public News() {
		super();
		// TODO Auto-generated constructor stub
	}
	public String getNewsTitle() {
		return newsTitle;
	}
	public void setNewsTitle(String newsTitle) {
		this.newsTitle = newsTitle;
	}
	public String getNewsContent() {
		return newsContent;
	}
	public void setNewsContent(String newsContent) {
		this.newsContent = newsContent;
	}
	public String getNewsIssuedate() {
		return newsIssuedate;
	}
	public void setNewsIssuedate(String newsIssuedate) {
		this.newsIssuedate = newsIssuedate;
	}
	public String getNewsIssuer() {
		return newsIssuer;
	}
	public void setNewsIssuer(String newsIssuer) {
		this.newsIssuer = newsIssuer;
	}
	public String getNewsPhotoName() {
		return newsPhotoName;
	}
	public void setNewsPhotoName(String newsPhotoName) {
		this.newsPhotoName = newsPhotoName;
	}
	public String getNewsPhotoPath() {
		return newsPhotoPath;
	}
	public void setNewsPhotoPath(String newsPhotoPath) {
		this.newsPhotoPath = newsPhotoPath;
	}

}
