package com.nxdcms.entity;
// Generated 2016-8-17 13:58:56 by Hibernate Tools 3.2.2.GA

/**
 * Notice generated by hbm2java
 */
public class Notice {

	private String noticeId;
	private String noticeContent;
	private String noticeDate;

	

	public String getNoticeId() {
		return this.noticeId;
	}

	public void setNoticeId(String noticeId) {
		this.noticeId = noticeId;
	}

	public String getNoticeContent() {
		return this.noticeContent;
	}

	public void setNoticeContent(String noticeContent) {
		this.noticeContent = noticeContent;
	}

	public String getNoticeDate() {
		return this.noticeDate;
	}

	public void setNoticeDate(String noticeDate) {
		this.noticeDate = noticeDate;
	}

}
