package com.nxdcms.entity;

import java.util.Date;

// Generated 2016-7-25 10:50:34 by Hibernate Tools 3.2.2.GA

/**
 * Subcompetition generated by hbm2java
 */
public class Subcompetition implements java.io.Serializable {

	private String Subcompid;
	private Competition competition;
	private String stuId1;// 负责人1
	private String stuId2;// 负责人2
	private String workName;// 队员
	private String college;// 学院
	private String teamName;// 团队名字
	private String compBookName;// 立项书名字
	private String compBookpath;// 立项书路径
	private String compAgreementName;// 协议名字
	private String compAgreementpath;// 协议
	private String awardName;// 获奖名字
	private String awardGrade;// 获奖等级
//	private String awardPicName;
	private String awardPicpath;// 获奖图片路径
	
	private Date awarddate; //获奖时间。
	private String awardIntr;// 获奖介绍
	private String teacher; // 指导老师的名字
	private String production;
	
//	
//	public String getAwardPicName() {
//		return awardPicName;
//	}
//
//	public void setAwardPicName(String awardPicName) {
//		this.awardPicName = awardPicName;
//	}

	public String getProduction() {
		return production;
	}

	public void setProduction(String production) {
		this.production = production;
	}

	public Date getAwarddate() {
		return awarddate;
	}

	public void setAwarddate(Date awarddate) {
		this.awarddate = awarddate;
	}

	public String getCompBookName() {
		return compBookName;
	}

	public void setCompBookName(String compBookName) {
		this.compBookName = compBookName;
	}

	public String getCompAgreementName() {
		return compAgreementName;
	}

	public void setCompAgreementName(String compAgreementName) {
		this.compAgreementName = compAgreementName;
	}

	public String getSubcompid() {
		return Subcompid;
	}

	public void setSubcompid(String subcompid) {
		Subcompid = subcompid;
	}

	public Competition getCompetition() {
		return competition;
	}

	public void setCompetition(Competition competition) {
		this.competition = competition;
	}

	public String getStuId1() {
		return stuId1;
	}

	public void setStuId1(String stuId1) {
		this.stuId1 = stuId1;
	}

	public String getStuId2() {
		return stuId2;
	}

	public void setStuId2(String stuId2) {
		this.stuId2 = stuId2;
	}

	public String getWorkName() {
		return workName;
	}

	public void setWorkName(String workName) {
		this.workName = workName;
	}

	public String getCollege() {
		return college;
	}

	public void setCollege(String college) {
		this.college = college;
	}

	public String getTeamName() {
		return teamName;
	}

	public void setTeamName(String teamName) {
		this.teamName = teamName;
	}

	public String getCompBookpath() {
		return compBookpath;
	}

	public void setCompBookpath(String compBookpath) {
		this.compBookpath = compBookpath;
	}

	public String getCompAgreementpath() {
		return compAgreementpath;
	}

	public void setCompAgreementpath(String compAgreementpath) {
		this.compAgreementpath = compAgreementpath;
	}

	public String getAwardName() {
		return awardName;
	}

	public void setAwardName(String awardName) {
		this.awardName = awardName;
	}

	public String getAwardGrade() {
		return awardGrade;
	}

	public void setAwardGrade(String awardGrade) {
		this.awardGrade = awardGrade;
	}

	public String getAwardPicpath() {
		return awardPicpath;
	}

	public void setAwardPicpath(String awardPicpath) {
		this.awardPicpath = awardPicpath;
	}

	public String getAwardIntr() {
		return awardIntr;
	}

	public void setAwardIntr(String awardIntr) {
		this.awardIntr = awardIntr;
	}

	public String getTeacher() {
		return teacher;
	}

	public void setTeacher(String teacher) {
		this.teacher = teacher;
	}

}
